### ISSUE TITLE
IdGenBuilder创建IdGen实例时，配置capacity大于10000时启动报错

### ISSUE THREAD

**Issue by rightkk** [zhuangjinjin/piccolo#7]
java.lang.IllegalArgumentException: data's length invalid, len:10000
	at io.github.ukuz.piccolo.api.external.common.Assert.isTrue(Assert.java:47)
	at io.github.ukuz.piccolo.client.id.snowflake.IdBuffer.write(IdBuffer.java:62)
	at io.github.ukuz.piccolo.client.id.snowflake.SnowflakeIdGenDelegate.writeData(SnowflakeIdGenDelegate.java:144)
	at io.github.ukuz.piccolo.client.id.snowflake.IdGenClientHandler.received(IdGenClientHandler.java:47)
	at io.github.ukuz.piccolo.client.common.MultiMessageClientHandler.lambda$received$0(MultiMessageClientHandler.java:53)

**Comment by zhuangjinjin** [comment]
已修复，上限是32767
